#!/usr/bin/env python3
"""
interactive_setup.py — Walkthrough for creating agent/crew model maps

Creates the character foundation (FOREVER SYSTEM §6) that the enforcer
affirmatively reminds at every pre-tool-call.

Generates:
  - agent-model-map.yaml (per agent)
  - crew-model-map.yaml (per crew)

Supports token-optimized tiering (flash iteration → quality final).
"""

import json
import os
import sys
import yaml
from datetime import datetime, timezone
from pathlib import Path


def now_iso():
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


# Canonical model tiers (single source of truth §1)
DEFAULT_MODEL_TIERS = {
    "qwen": {
        "maximum_reasoning": "qwen3-max",
        "strong_reasoning": "qwen3.5-plus",
        "fast_iteration": "qwen3.5-flash",
        "bulk_operations": "qwen-turbo",
        "vision_high": "qwen3-vl-plus",
        "vision_fast": "qwen3-vl-flash",
        "image_iteration": "wan2.2-t2i-flash",
        "image_final": "wan2.6-t2i",
        "video_iteration": "wan2.6-i2v-flash",
        "video_final": "wan2.7-i2v",
        "voice_iteration": "cosyvoice-v3-flash",
        "voice_final": "cosyvoice-v3-plus",
    },
    "openai": {
        "maximum_reasoning": "o1-pro",
        "strong_reasoning": "o1",
        "fast_iteration": "gpt-4o-mini",
        "bulk_operations": "gpt-3.5-turbo",
        "vision_high": "gpt-4o",
        "vision_fast": "gpt-4o-mini",
        "image_iteration": "dall-e-3",
        "image_final": "dall-e-3",
        "video_iteration": "sora",
        "video_final": "sora",
        "voice_iteration": "tts-1",
        "voice_final": "tts-1-hd",
    },
    "anthropic": {
        "maximum_reasoning": "claude-opus-4",
        "strong_reasoning": "claude-sonnet-4",
        "fast_iteration": "claude-haiku-3.5",
        "bulk_operations": "claude-haiku-3",
        "vision_high": "claude-opus-4",
        "vision_fast": "claude-sonnet-4",
        "image_iteration": "dall-e-3",
        "image_final": "dall-e-3",
        "video_iteration": "external",
        "video_final": "external",
        "voice_iteration": "external",
        "voice_final": "external",
    },
}


# Default phase model map (can be customized)
DEFAULT_PHASE_MODEL_MAP = {
    "PHASE-0": {"create": "strong_reasoning", "revise": "fast_iteration"},
    "PHASE-1": {"create": "maximum_reasoning", "revise": "strong_reasoning"},
    "PHASE-2": {"create": "strong_reasoning", "revise": "fast_iteration"},
    "PHASE-3": {"create": "strong_reasoning", "revise": "fast_iteration"},
    "PHASE-4": {"evaluate": "vision_high", "quick_check": "vision_fast"},
    "PHASE-5": {"assemble": "fast_iteration"},
}


# Token reduction strategies (FOREVER SYSTEM §6 - affirmative reminders)
DEFAULT_STRATEGIES = [
    "Flash-first iteration: always generate with flash models first. Only upgrade to quality after evaluation passes.",
    "Retrieve don't remember: use semantic search to retrieve only relevant context. Never load full project.",
    "Working memory isolation: each agent loads only its own input artifacts, not the entire project.",
    "Regenerate only failure: when Quality Reviewer fails a scene, only that scene regenerates. Everything else stays.",
    "Thinking mode off by default: enable thinking only for creative vision and final review. Disable for all other tasks.",
    "Context caching: cache Creative Brief in context for repeated reference across all agents.",
    "Batch API for offline work: use Batch API (50% off) for non-realtime generation like bulk storyboard renders.",
    "Short clips first: generate 2-3 second flash clips for motion validation before committing to 5-10 second quality renders.",
]


def load_yaml(path: Path) -> dict:
    if path.exists():
        return yaml.safe_load(path.read_text()) or {}
    return {}


def save_yaml(path: Path, data: dict):
    path.parent.mkdir(parents=True, exist_ok=True)
    # Add layer metadata (§3)
    if "_layer" not in data:
        data["_layer"] = {
            "id": f"{path.stem}-v1",
            "created": now_iso(),
            "supersedes": None,
            "description": f"Generated by interactive_setup.py"
        }
    yaml_str = yaml.dump(data, sort_keys=False, default_flow_style=False)
    path.write_text(yaml_str)


def prompt_with_default(prompt: str, default: str = "") -> str:
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        while True:
            user_input = input(f"{prompt}: ").strip()
            if user_input:
                return user_input
            print("  Required. Please enter a value.")


def prompt_yes_no(prompt: str, default: bool = True) -> bool:
    default_str = "Y/n" if default else "y/N"
    user_input = input(f"{prompt} [{default_str}]: ").strip().lower()
    if not user_input:
        return default
    return user_input in ("y", "yes", "true", "1")


def prompt_choice(prompt: str, choices: list, default: str = None) -> str:
    print(f"{prompt}")
    for i, choice in enumerate(choices, 1):
        marker = " (default)" if choice == default else ""
        print(f"  {i}. {choice}{marker}")
    while True:
        user_input = input(f"Choice [1-{len(choices)}]: ").strip()
        if not user_input and default:
            return default
        try:
            idx = int(user_input) - 1
            if 0 <= idx < len(choices):
                return choices[idx]
        except ValueError:
            pass
        print("  Invalid choice. Try again.")


def setup_agent(workspace: Path, blueprint_phases: list = None) -> dict:
    """Interactive agent model map setup."""
    print(f"\n{'='*60}")
    print(f"AGENT SETUP: {workspace.name}")
    print(f"{'='*60}")
    
    # Detect existing identity
    agent_json = workspace / "agent.json"
    if agent_json.exists():
        try:
            data = json.loads(agent_json.read_text())
            agent_id = data.get("agent_id", workspace.name)
            agent_type = data.get("agent_type", "unknown")
        except:
            agent_id = workspace.name
            agent_type = "unknown"
    else:
        agent_id = workspace.name
        agent_type = "unknown"
    
    print(f"\nDetected agent: {agent_id} (type: {agent_type})")
    
    agent_id = prompt_with_default("Agent ID", agent_id)
    agent_type = prompt_with_default("Agent Type (ui, backend, blockchain, lead, qa, etc.)", agent_type)
    crew_id = prompt_with_default("Crew ID (optional)", "")
    
    # Model provider
    provider = prompt_choice("Model Provider", ["qwen", "openai", "anthropic", "custom"], "qwen")
    
    if provider == "custom":
        print("\nCustom provider — you'll define model tiers manually.")
        model_tiers = {}
        for tier in ["maximum_reasoning", "strong_reasoning", "fast_iteration", "bulk_operations",
                     "vision_high", "vision_fast", "image_iteration", "image_final",
                     "video_iteration", "video_final", "voice_iteration", "voice_final"]:
            model_tiers[tier] = prompt_with_default(f"  {tier}", "")
    else:
        model_tiers = DEFAULT_MODEL_TIERS[provider].copy()
        print(f"\nUsing {provider} model tiers:")
        for tier, model in model_tiers.items():
            print(f"  {tier}: {model}")
        if prompt_yes_no("\nCustomize any model tiers?", False):
            for tier in model_tiers:
                model_tiers[tier] = prompt_with_default(f"  {tier}", model_tiers[tier])
    
    # Phase model map
    print(f"\nPhase Model Assignments")
    print(f"  (create = initial work, revise = iteration loops)")
    print(f"  Available tiers: {', '.join(model_tiers.keys())}")
    
    if blueprint_phases:
        print(f"\nBlueprint has phases: {', '.join(blueprint_phases)}")
        use_blueprint_phases = prompt_yes_no("Use blueprint phases?", True)
        phases = blueprint_phases if use_blueprint_phases else []
    else:
        phases = []
    
    if not phases:
        # Default phases
        phases = ["PHASE-0", "PHASE-1", "PHASE-2", "PHASE-3", "PHASE-4", "PHASE-5"]
    
    phase_model_map = {}
    for phase in phases:
        print(f"\n  {phase}:")
        if "create" in DEFAULT_PHASE_MODEL_MAP.get(phase, {}):
            create_tier = prompt_with_default(f"    create tier", DEFAULT_PHASE_MODEL_MAP[phase].get("create", "strong_reasoning"))
            revise_tier = prompt_with_default(f"    revise tier", DEFAULT_PHASE_MODEL_MAP[phase].get("revise", "fast_iteration"))
            phase_model_map[phase] = {"create": create_tier, "revise": revise_tier}
        elif "evaluate" in DEFAULT_PHASE_MODEL_MAP.get(phase, {}):
            evaluate_tier = prompt_with_default(f"    evaluate tier", DEFAULT_PHASE_MODEL_MAP[phase].get("evaluate", "vision_high"))
            quick_tier = prompt_with_default(f"    quick_check tier", DEFAULT_PHASE_MODEL_MAP[phase].get("quick_check", "vision_fast"))
            phase_model_map[phase] = {"evaluate": evaluate_tier, "quick_check": quick_tier}
        elif "assemble" in DEFAULT_PHASE_MODEL_MAP.get(phase, {}):
            assemble_tier = prompt_with_default(f"    assemble tier", DEFAULT_PHASE_MODEL_MAP[phase].get("assemble", "fast_iteration"))
            phase_model_map[phase] = {"assemble": assemble_tier}
        else:
            create_tier = prompt_with_default(f"    create tier", "strong_reasoning")
            revise_tier = prompt_with_default(f"    revise tier", "fast_iteration")
            phase_model_map[phase] = {"create": create_tier, "revise": revise_tier}
    
    # Task overrides
    print(f"\nTask-Specific Overrides (optional)")
    print(f"  e.g., 'video-generation' → iteration/final, 'screen-specs' → create/revise")
    task_overrides = {}
    if prompt_yes_no("Add task overrides?", False):
        while True:
            task_name = input("  Task name (empty to finish): ").strip()
            if not task_name:
                break
            print(f"  {task_name}:")
            if "video" in task_name.lower():
                iter_tier = prompt_with_default(f"    iteration tier", "video_iteration")
                final_tier = prompt_with_default(f"    final tier", "video_final")
                task_overrides[task_name] = {"iteration": iter_tier, "final": final_tier}
            elif "image" in task_name.lower() or "storyboard" in task_name.lower():
                iter_tier = prompt_with_default(f"    iteration tier", "image_iteration")
                final_tier = prompt_with_default(f"    final tier", "image_final")
                task_overrides[task_name] = {"iteration": iter_tier, "final": final_tier}
            elif "voice" in task_name.lower() or "audio" in task_name.lower():
                iter_tier = prompt_with_default(f"    iteration tier", "voice_iteration")
                final_tier = prompt_with_default(f"    final tier", "voice_final")
                task_overrides[task_name] = {"iteration": iter_tier, "final": final_tier}
            else:
                create_tier = prompt_with_default(f"    create tier", "strong_reasoning")
                revise_tier = prompt_with_default(f"    revise tier", "fast_iteration")
                task_overrides[task_name] = {"create": create_tier, "revise": revise_tier}
    
    # Strategies
    print(f"\nToken Reduction Strategies (affirmative reminders §6)")
    strategies = DEFAULT_STRATEGIES.copy()
    if prompt_yes_no("Use default strategies?", True):
        pass
    else:
        strategies = []
        print("Enter strategies (empty to finish):")
        while True:
            s = input("  Strategy: ").strip()
            if not s:
                break
            strategies.append(s)
    
    # Build config
    config = {
        "agent_id": agent_id,
        "agent_type": agent_type,
        "crew_id": crew_id if crew_id else None,
        "model_provider": provider,
        "model_tiers": model_tiers,
        "phase_model_map": phase_model_map,
        "task_overrides": task_overrides,
        "strategies": strategies,
        "created": now_iso(),
        "version": "1.0"
    }
    
    return config


def setup_crew(workspace: Path, agent_configs: dict = None) -> dict:
    """Interactive crew model map setup."""
    print(f"\n{'='*60}")
    print(f"CREW SETUP: {workspace.name}")
    print(f"{'='*60}")
    
    # Detect crew.json
    crew_json = workspace / "crew.json"
    if crew_json.exists():
        try:
            data = json.loads(crew_json.read_text())
            crew_id = data.get("crew_id", workspace.name)
            crew_mode = data.get("crew_mode", "production")
            roster = data.get("agents", [])
        except:
            crew_id = workspace.name
            crew_mode = "production"
            roster = []
    else:
        crew_id = workspace.name
        crew_mode = "production"
        roster = []
    
    print(f"\nDetected crew: {crew_id} (mode: {crew_mode})")
    print(f"Roster: {len(roster)} agents")
    
    crew_id = prompt_with_default("Crew ID", crew_id)
    crew_mode = prompt_choice("Crew Mode", ["development", "production"], crew_mode)
    
    agents = []
    if roster:
        print(f"\nExisting roster:")
        for r in roster:
            print(f"  - {r.get('agent_id')} ({r.get('agent_type')})")
        use_existing = prompt_yes_no("Use existing roster?", True)
        if use_existing:
            for r in roster:
                agent_id = r.get("agent_id")
                agent_type = r.get("agent_type", "unknown")
                model_map = f"../agents/{agent_id}/agent-model-map.yaml"
                phases = prompt_with_default(f"  {agent_id} phases (comma-separated)", "").split(",")
                phases = [p.strip() for p in phases if p.strip()]
                scope = prompt_choice(f"  {agent_id} scope", ["phase-owner", "module"], "phase-owner")
                modules = []
                if scope == "module":
                    modules = prompt_with_default(f"  {agent_id} modules (comma-separated MOD-XXX)", "").split(",")
                    modules = [m.strip() for m in modules if m.strip()]
                agents.append({
                    "agent_id": agent_id,
                    "agent_type": agent_type,
                    "model_map": model_map,
                    "phases": phases,
                    "scope": scope,
                    "modules": modules
                })
    
    if not agents:
        print("\nDefine agents (empty agent_id to finish):")
        while True:
            agent_id = input("  Agent ID: ").strip()
            if not agent_id:
                break
            agent_type = prompt_with_default(f"  {agent_id} type", "unknown")
            model_map = prompt_with_default(f"  {agent_id} model map path", f"../agents/{agent_id}/agent-model-map.yaml")
            phases = prompt_with_default(f"  {agent_id} phases (comma-separated)", "").split(",")
            phases = [p.strip() for p in phases if p.strip()]
            scope = prompt_choice(f"  {agent_id} scope", ["phase-owner", "module"], "phase-owner")
            modules = []
            if scope == "module":
                modules = prompt_with_default(f"  {agent_id} modules (comma-separated MOD-XXX)", "").split(",")
                modules = [m.strip() for m in modules if m.strip()]
            agents.append({
                "agent_id": agent_id,
                "agent_type": agent_type,
                "model_map": model_map,
                "phases": phases,
                "scope": scope,
                "modules": modules
            })
    
    # Shared model pool (cost optimization)
    print(f"\nShared Model Pool (optional - for cost optimization)")
    shared_pool = {}
    if prompt_yes_no("Configure shared model pool?", False):
        provider = list(DEFAULT_MODEL_TIERS.keys())[0]
        for tier, model in DEFAULT_MODEL_TIERS[provider].items():
            if tier in ["maximum_reasoning", "strong_reasoning", "vision_high"]:
                concurrent = prompt_with_default(f"  {tier} ({model}) max concurrent", "1")
                shared_pool[tier] = {"model": model, "max_concurrent": int(concurrent)}
            elif tier in ["fast_iteration", "bulk_operations", "vision_fast"]:
                shared_pool[tier] = {"model": model, "max_concurrent": "unlimited"}
    
    config = {
        "crew_id": crew_id,
        "crew_mode": crew_mode,
        "agents": agents,
        "shared_model_pool": shared_pool if shared_pool else None,
        "created": now_iso(),
        "version": "1.0"
    }
    
    return config


def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="Interactive setup for agent/crew model maps")
    parser.add_argument("workspace", nargs="?", default=".", help="Workspace directory")
    parser.add_argument("--agent", action="store_true", help="Force agent setup")
    parser.add_argument("--crew", action="store_true", help="Force crew setup")
    parser.add_argument("--blueprint", help="Blueprint file to extract phases from")
    parser.add_argument("--noninteractive", action="store_true", help="Non-interactive mode (use defaults)")
    parser.add_argument("--output-agent", help="Output path for agent model map")
    parser.add_argument("--output-crew", help="Output path for crew model map")
    args = parser.parse_args()
    
    workspace = Path(args.workspace).resolve()
    
    # Parse blueprint for phases
    blueprint_phases = None
    if args.blueprint:
        bp_path = Path(args.blueprint).resolve()
        if bp_path.exists():
            content = bp_path.read_text()
            import re
            phase_pattern = r"^###\s*(?:PHASE-)?(\d+):\s*([^\n]+)"
            phases = []
            for match in re.finditer(phase_pattern, content, re.MULTILINE):
                phases.append(f"PHASE-{match.group(1)}")
            if phases:
                blueprint_phases = phases
                print(f"Found blueprint phases: {', '.join(blueprint_phases)}")
    
    # Detect identity
    from discover_agents import detect_identity
    identity = detect_identity(workspace)
    
    if args.agent or identity["type"] == "agent":
        print(f"\nDetected: AGENT ({identity.get('agent_id', workspace.name)})")
        config = setup_agent(workspace, blueprint_phases)
        
        output_path = Path(args.output_agent) if args.output_agent else workspace / "agent-model-map.yaml"
        save_yaml(output_path, config)
        print(f"\n✓ Agent model map saved: {output_path}")
        
        # Validate with skill_enhance.py if available
        print(f"\nRun validation:")
        print(f"  python3 .hermes/skills/skill-creator/scripts/skill_enhance.py update \\")
        print(f"    --path {workspace} --tier enterprise --noninteractive")
        
    elif args.crew or identity["type"] == "crew":
        print(f"\nDetected: CREW ({identity.get('crew_id', workspace.name)})")
        
        # First setup each agent
        agent_configs = {}
        for agent_info in identity.get("agents", []):
            agent_path = Path(agent_info["path"])
            print(f"\n{'='*60}")
            print(f"Setting up agent: {agent_info['agent_id']}")
            print(f"{'='*60}")
            agent_config = setup_agent(agent_path, blueprint_phases)
            agent_output = agent_path / "agent-model-map.yaml"
            save_yaml(agent_output, agent_config)
            agent_configs[agent_info["agent_id"]] = agent_config
        
        # Then crew
        config = setup_crew(workspace, agent_configs)
        
        output_path = Path(args.output_crew) if args.output_crew else workspace / "crew-model-map.yaml"
        save_yaml(output_path, config)
        print(f"\n✓ Crew model map saved: {output_path}")
        
    else:
        print(f"\nDetected: PROJECT (no agent/crew identity)")
        print(f"Choose setup type:")
        choice = prompt_choice("Setup type", ["agent", "crew", "project-only"])
        
        if choice == "agent":
            config = setup_agent(workspace, blueprint_phases)
            output_path = Path(args.output_agent) if args.output_agent else workspace / "agent-model-map.yaml"
            save_yaml(output_path, config)
            print(f"\n✓ Agent model map saved: {output_path}")
        elif choice == "crew":
            config = setup_crew(workspace)
            output_path = Path(args.output_crew) if args.output_crew else workspace / "crew-model-map.yaml"
            save_yaml(output_path, config)
            print(f"\n✓ Crew model map saved: {output_path}")
        else:
            print("Project-only setup — no model maps created.")
            print("Run with --agent or --crew to create configs.")


if __name__ == "__main__":
    main()