#!/usr/bin/env python3
"""
skill-creator/__init__.py — Enterprise skill scaffolder + toolchain entry point.

Runs as either a Python module (`import skill_creator`) OR a CLI scaffolder
(`python3 __init__.py --scaffold my-new-skill --path /where/`). Per the rule
that __init__.py contains SCAFFOLDING for whatever the skill is responsible
for curating, and skill-creator's responsibility is creating skills, this
IS the scaffolder for new skills.

The scaffolded skeleton contains EXACTLY the 5 required root items:
  __init__.py       — scaffolding script for the new skill (uses this template)
  SKILL.md          — frontmatter + body template (contains REPLACE_ME_* markers)
  scripts/          — empty; author populates with real content
  references/       — empty; author populates with real content
  <name>.skill      — regenerated by package_skills.py; not created here

Nested `references/lessons/` is created only on demand (author's choice), and
does NOT affect enterprise tier classification.

NEVER creates `assets/`. Assets belong inside the specific script/reference
files that use them, not at the skill root.
"""
import argparse
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

# ─── Package metadata (importable) ────────────────────────────────────────

NAME = "skill-creator"
VERSION = "3.0.14"
PREVIOUS_VERSION = "2.1.1"
FORK_ORIGIN = "_curated/skill-creator@2.1.1"
FORK_NOTE = ("Every mutating script is directly invokable. skill_enhance.py "
             "sequences the same 11-step pipeline by calling each script "
             "directly.")
DESCRIPTION = "Skill scaffolder, validator, packager, and upgrader"
LICENSE = "MIT"

VALIDATION_PIPELINE = [
    "validate.py --basic",      # Downstream callers should use --basic
    "validate.py",              # Enterprise gate (before packaging)
    "test_script.py",           # Script functionality
    "package_skills.py",        # Pack with version bump
    "validate.py",              # Post-pack sanity check
]

__skill__ = NAME
__version__ = VERSION
__previous_version__ = PREVIOUS_VERSION
__all__ = ["NAME", "VERSION", "PREVIOUS_VERSION", "FORK_ORIGIN", "FORK_NOTE",
           "DESCRIPTION", "LICENSE", "VALIDATION_PIPELINE",
           "scaffold", "integrate", "convert", "add_lesson"]

# ─── Scaffolding templates ────────────────────────────────────────────────

SKILL_MD_TEMPLATE = """---
name: {name}
description: "REPLACE_ME_DESCRIBE_WHAT_THIS_SKILL_DOES_AND_WHEN_TO_USE_IT_INCLUDE_CONCRETE_TRIGGERS_SO_ANOTHER_AGENT_KNOWS_TO_INVOKE_THIS_SKILL_MINIMUM_100_MAXIMUM_1024_CHARACTERS"
version: 0.1.0
license: MIT
metadata:
  category: REPLACE_ME_CATEGORY
  complexity: enterprise
  tags:
{tag_lines}
---

# {display_name}

REPLACE_ME_ONE_TO_TWO_SENTENCE_SUMMARY_OF_WHAT_THIS_SKILL_DOES_AND_WHY_A_READER_WOULD_CARE.

## When to use

REPLACE_ME_LIST_CONCRETE_SCENARIOS_THAT_SHOULD_TRIGGER_THIS_SKILL.

## Toolchain

REPLACE_ME_LIST_EACH_SCRIPT_IN_scripts_WITH_ONE_LINE_PURPOSE_EACH.

## References

REPLACE_ME_LIST_EACH_DOC_IN_references_WITH_ONE_LINE_PURPOSE_EACH.

## Compatibility

REPLACE_ME_ONE_LINE_ON_WHAT_ENVIRONMENTS_THIS_RUNS_IN.
"""

# Scaffolded skill's __init__.py — the CHILD skill's scaffolder (skills that
# aren't skill-creator scaffold their own domain — e.g. an autowatch skill
# scaffolds new watched-dir configs; a payments skill scaffolds new payment
# integrations. Author fills in the scaffold() body for their skill's domain.)
CHILD_INIT_TEMPLATE = '''#!/usr/bin/env python3
"""
{name}/__init__.py — scaffolder + integrator for whatever {name} curates.

Per the project rule, every skill's __init__.py contains the scaffolding logic
for the skill's own domain. Fill in scaffold() with what a new instance of
this skill's output looks like, and integrate() with how to plug it into a
target project.
"""
import argparse
from pathlib import Path

__skill__ = "{name}"
__version__ = "0.1.0"
__created__ = "{timestamp}"


def scaffold(target_name, base_dir):
    """Create a new instance of whatever this skill scaffolds.

    Example (replace with domain-specific logic):
        target_dir = Path(base_dir) / target_name
        target_dir.mkdir(parents=True, exist_ok=True)
        # ... write files, generate config, etc.
    """
    raise NotImplementedError(
        "Fill scaffold() with the logic for scaffolding a new {name} instance."
    )


def integrate(target_path, name, dry_run=False):
    """Integrate a scaffolded instance into an existing project."""
    raise NotImplementedError(
        "Fill integrate() with the logic for wiring {name} into a project."
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Scaffolder for {name} skill")
    parser.add_argument("--scaffold", help="Name of new instance to scaffold")
    parser.add_argument("--integrate", help="Target path to integrate into")
    parser.add_argument("--name", help="Name of the instance being integrated")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.scaffold:
        scaffold(args.scaffold, Path.cwd())
    elif args.integrate:
        integrate(Path(args.integrate), args.name or "unknown", args.dry_run)
    else:
        parser.print_help()
'''


def _slug(name):
    s = re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-")
    return s[:64]


def _display(name):
    return name.replace("-", " ").title()


def _tag_lines(count):
    return "\n".join(
        f"    - REPLACE_ME_TAG_{i+1}_natural_language_phrase_that_would_auto_trigger_this_skill"
        for i in range(count)
    )


# ─── Public API ───────────────────────────────────────────────────────────

def scaffold(skill_name, base_dir, force=False, tier="enterprise",
             dry_run=False):
    """Create a new skill's root scaffold under base_dir.

    Args:
      skill_name: raw name — will be slugified to hyphen-case
      base_dir:   Path or str; the parent directory (e.g. .../curated/)
      force:      if dest exists, PRESERVE its SKILL.md/__init__.py by moving
                  them aside with a .pre-scaffold timestamp suffix (nothing is
                  ever deleted), then write fresh templates
      tier:       "enterprise" (default, 7 tags) — 'basic' is not accepted
                  because per project rule init only scaffolds enterprise-rated
      dry_run:    report what would be created without writing anything

    Returns dict with status + path + next-step guidance.
    """
    if tier != "enterprise":
        raise ValueError("scaffold() only creates enterprise-tier skills. "
                         "Use validate.py --basic to inspect existing basic skills; "
                         "never scaffold a basic-tier skeleton.")

    name = _slug(skill_name)
    if not name:
        raise ValueError(f"skill name {skill_name!r} slugs to empty")
    parent = Path(base_dir).resolve()
    if not parent.exists():
        raise FileNotFoundError(f"parent {parent} does not exist")

    dest = parent / name
    if dest.exists() and not force:
        raise FileExistsError(f"{dest} exists; pass force=True to re-scaffold "
                              "(existing files are moved aside, never deleted)")
    preserved = []
    if dest.exists() and force and not dry_run:
        # NEVER delete: move the files we'd regenerate aside, timestamped
        stamp = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
        for fname in ("SKILL.md", "__init__.py"):
            existing = dest / fname
            if existing.is_file():
                aside = dest / f"{fname}.pre-scaffold-{stamp}"
                existing.rename(aside)
                preserved.append(str(aside))

    if dry_run:
        return {
            "operation": "scaffold",
            "skill": name,
            "path": str(dest),
            "tier": "enterprise",
            "dry_run": True,
            "would_create": ["SKILL.md", "__init__.py", "scripts/", "references/"],
            "would_preserve": [f"{f} → {f}.pre-scaffold-<ts>" for f in
                               ("SKILL.md", "__init__.py")
                               if (dest / f).is_file()] if dest.exists() else [],
        }

    dest.mkdir(parents=True, exist_ok=True)
    (dest / "scripts").mkdir(exist_ok=True)
    (dest / "references").mkdir(exist_ok=True)
    # NOTE: assets/ is intentionally NOT created. Nested references/lessons/
    # is created on-demand by the author, not here.

    # Write SKILL.md (7 tags because enterprise-only)
    (dest / "SKILL.md").write_text(SKILL_MD_TEMPLATE.format(
        name=name,
        display_name=_display(name),
        tag_lines=_tag_lines(7),
    ), encoding="utf-8")

    # Write child __init__.py (scaffolder-in-training for the new skill's own domain)
    (dest / "__init__.py").write_text(CHILD_INIT_TEMPLATE.format(
        name=name,
        timestamp=datetime.now(timezone.utc).isoformat(),
    ), encoding="utf-8")

    return {
        "operation": "scaffold",
        "skill": name,
        "path": str(dest),
        "tier": "enterprise",
        "preserved": preserved,
        "next_steps": [
            f"Edit {dest}/SKILL.md — fill every REPLACE_ME_* marker",
            f"Add ≥3 real scripts to {dest}/scripts/",
            f"Add ≥5 real reference docs to {dest}/references/",
            f"Fill scaffold() + integrate() bodies in {dest}/__init__.py "
            f"with logic specific to what this skill curates",
            f"Validate: python3 {Path(__file__).parent}/scripts/validate.py {dest}",
            f"Package:  python3 {Path(__file__).parent}/scripts/package_skills.py "
            f"--skills-root {parent} --skill {name}",
        ],
    }


LESSON_TEMPLATE = """---
title: {title}
category: REPLACE_ME_CATEGORY
failure: REPLACE_ME_CONCRETE_SYMPTOM_WHAT_BROKE_OR_SURPRISED
root_cause: REPLACE_ME_WHY_IT_HAPPENED
resolution: REPLACE_ME_WHAT_FIXED_IT
prevention: REPLACE_ME_THE_RULE_OR_PATTERN_GOING_FORWARD
date: {date}
verified: false
---

(optional prose elaboration below, only if the frontmatter fields alone don't
capture the full context)
"""


def convert(existing_dir, dry_run=False):
    """Non-destructively bring an EXISTING directory up to skill structure.

    Creates only what's missing (scripts/, references/, a minimal SKILL.md
    shell with REPLACE_ME markers). Never moves, renames, or deletes anything
    that's already there — run auto_fix.py + validate.py afterward for that.
    """
    d = Path(existing_dir).resolve()
    if not d.is_dir():
        raise FileNotFoundError(f"{d} is not a directory")
    name = _slug(d.name)
    created = []
    for sub in ("scripts", "references"):
        if not (d / sub).is_dir():
            if not dry_run:
                (d / sub).mkdir()
            created.append(f"{sub}/")
    if not (d / "SKILL.md").is_file():
        if not dry_run:
            (d / "SKILL.md").write_text(SKILL_MD_TEMPLATE.format(
                name=name, display_name=_display(name),
                tag_lines=_tag_lines(7)), encoding="utf-8")
        created.append("SKILL.md (template — fill every REPLACE_ME marker)")
    if not (d / "__init__.py").is_file():
        if not dry_run:
            (d / "__init__.py").write_text(CHILD_INIT_TEMPLATE.format(
                name=name,
                timestamp=datetime.now(timezone.utc).isoformat()),
                encoding="utf-8")
        created.append("__init__.py (template — fill scaffold()/integrate())")
    return {"operation": "convert", "path": str(d), "dry_run": dry_run,
            "created": created,
            "next": "populate templates, then run scripts/validate.py"}


def add_lesson(skill_dir, title, dry_run=False):
    """Add a structured lesson file to <skill>/references/lessons/."""
    d = Path(skill_dir).resolve()
    if not (d / "SKILL.md").is_file():
        raise FileNotFoundError(f"{d} has no SKILL.md — not a skill root")
    lessons = d / "references" / "lessons"
    fname = _slug(title) + ".md"
    dest = lessons / fname
    if dest.exists():
        raise FileExistsError(f"lesson already exists: {dest}")
    if not dry_run:
        lessons.mkdir(parents=True, exist_ok=True)
        dest.write_text(LESSON_TEMPLATE.format(
            title=title.strip(),
            date=datetime.now(timezone.utc).strftime("%Y-%m-%d")),
            encoding="utf-8")
    return {"operation": "add_lesson", "path": str(dest), "dry_run": dry_run}


def integrate(target_path, skill_name, dry_run=False):
    """Wire a scaffolded skill into an external project (import + register).

    Downstream skills override this for their specific integration story;
    skill-creator itself provides a generic 'copy + append import' fallback.
    """
    tgt = Path(target_path)
    if not tgt.exists():
        raise FileNotFoundError(f"target {tgt} does not exist")
    action = "would copy" if dry_run else "copied"
    return {"operation": "integrate", "skill": skill_name,
            "target": str(tgt), "action": action}


# ─── CLI ──────────────────────────────────────────────────────────────────

def _cli():
    ap = argparse.ArgumentParser(
        description="skill-creator — scaffold, convert, and integrate skills")
    ap.add_argument("--scaffold", help="Scaffold a new skill with this name")
    ap.add_argument("--path", help="Parent dir under which to create the skill")
    ap.add_argument("--convert", help="Existing dir to bring up to skill structure (creates only what's missing)")
    ap.add_argument("--add-lesson", help="Lesson title to add to a skill (use with --skill-dir)")
    ap.add_argument("--skill-dir", help="Skill dir (used with --add-lesson)")
    ap.add_argument("--integrate", help="Target project path to integrate into")
    ap.add_argument("--name", help="Skill name (used with --integrate)")
    ap.add_argument("--force", action="store_true",
                    help="Re-scaffold over existing (files moved aside, never deleted)")
    ap.add_argument("--dry-run", action="store_true", help="Preview without writing")
    args = ap.parse_args()
    if args.scaffold:
        if not args.path:
            sys.exit("ERROR: --path is required with --scaffold")
        r = scaffold(args.scaffold, args.path, force=args.force,
                     dry_run=args.dry_run)
        if r.get("dry_run"):
            print(f"[dry-run] would scaffold {r['skill']} at {r['path']}")
            for w in r.get("would_preserve", []):
                print(f"  would preserve: {w}")
        else:
            print(f"✓ scaffolded {r['skill']} at {r['path']} (enterprise-tier)")
            for p in r.get("preserved", []):
                print(f"  preserved existing: {p}")
            for s in r["next_steps"]:
                print(f"  → {s}")
    elif args.convert:
        r = convert(args.convert, dry_run=args.dry_run)
        prefix = "[dry-run] would create" if args.dry_run else "created"
        print(f"✓ convert {r['path']}")
        for c in r["created"]:
            print(f"  {prefix}: {c}")
        print(f"  → {r['next']}")
    elif args.add_lesson:
        if not args.skill_dir:
            sys.exit("ERROR: --skill-dir is required with --add-lesson")
        r = add_lesson(args.skill_dir, args.add_lesson, dry_run=args.dry_run)
        print(f"✓ {'[dry-run] would create' if args.dry_run else 'created'} "
              f"lesson: {r['path']}")
    elif args.integrate:
        r = integrate(args.integrate, args.name or "unknown", args.dry_run)
        print(r)
    else:
        ap.print_help()


if __name__ == "__main__":
    _cli()
