#!/usr/bin/env python3
"""Scanner engine: enumerates authors, committers, trailers and repo
classification inputs from the full history. This is the ONLY module that
reads commit identities; every other module consumes its report."""
from __future__ import annotations

import json
import re
from collections import Counter, OrderedDict
from pathlib import Path

from gitsanitize_core import GSError, run_git

TRAILER_RE = re.compile(
    r"^([A-Za-z][A-Za-z0-9-]{1,63}):[ \t]+(.+)$"
)

BOT_HINTS = (
    "bot", "no-reply@github.com", "users.noreply.github.com",
    "dependabot", "actions@", "codecov", "renovate",
)

GENERATED_HINTS = (
    "generated by", "auto-generated", "automatically generated",
    "generated with", "codegen", "synthetic",
)


class ScanResult:
    def __init__(self):
        self.total_commits = 0
        self.authors: list[dict] = []          # [{name,email,count}]
        self.committers: list[dict] = []
        self.trailers: list[dict] = []         # [{label,count,sample,raw}]
        self.remote_url: str | None = None
        self.branches: list[str] = []
        self.tags: list[str] = []
        self.auto_commits = 0
        self.generated_hint_commits = 0
        self.head_sha: str | None = None

    def author_count(self) -> int:
        return len(self.authors)

    def owner_dominance(self) -> float:
        if not self.total_commits:
            return 0.0
        top = max((a["count"] for a in self.authors), default=0)
        return round(100.0 * top / self.total_commits, 1)

    def classify(self, rc: dict) -> str:
        """Return PERSONAL/OPEN_SOURCE/ORGANIZATION/FORK/MIRROR/GENERATED."""
        mode = rc.get("mode", "auto")
        if mode != "auto":
            return str(mode).upper()
        owner_dom = rc.get("owner_dominance", 80)
        if self.remote_url:
            low = self.remote_url.lower()
            if "mirror" in low:
                return "MIRROR"
            if "/fork/" in low or low.endswith(".fork.git"):
                return "FORK"
        if self.total_commits and self.generated_hint_commits == self.total_commits:
            return "GENERATED"
        dom = self.owner_dominance()
        if dom >= float(owner_dom):
            return "PERSONAL"
        corp = _looks_corporate(self.authors)
        return "ORGANIZATION" if corp else "OPEN_SOURCE"


def _looks_corporate(authors: list[dict]) -> bool:
    domains = Counter()
    for a in authors:
        dom = (a.get("email") or "").split("@")[-1].lower()
        if dom:
            domains[dom] += a.get("count", 0)
    total = sum(domains.values())
    if not total:
        return False
    for dom, count in domains.most_common(3):
        if count / total > 0.5 and dom not in ("gmail.com", "yahoo.com", "hotmail.com",
                                               "outlook.com", "users.noreply.github.com",
                                               "qq.com", "163.com", "proton.me", "icloud.com"):
            return True
    return False


def _fmt_map(counter: Counter) -> list[dict]:
    out = []
    for (name, email), count in counter.most_common():
        out.append({"name": name, "email": email, "count": count})
    return out


def scan(repo: Path, deep: bool = False) -> ScanResult:
    if not repo.exists() or not (repo / ".git").exists():
        raise GSError(f"not a git repository: {repo}")

    result = ScanResult()
    proc = run_git(
        ["log", "--all", "--pretty=format:%an%x1f%ae%x1f%cn%x1f%ce"],
        repo,
    )
    result.total_commits = proc.stdout.count("\n") + (1 if proc.stdout.strip() else 0)

    authors = Counter()
    committers = Counter()
    for line in proc.stdout.splitlines():
        if not line:
            continue
        parts = line.split("\x1f")
        if len(parts) < 4:
            continue
        an, ae, cn, ce = parts[:4]
        authors[(an, ae)] += 1
        committers[(cn, ce)] += 1
        if any(h in (ae + " " + an).lower() for h in BOT_HINTS):
            result.auto_commits += 1
    result.authors = _fmt_map(authors)
    result.committers = _fmt_map(committers)

    result.branches = sorted(
        b.strip() for b in run_git(["branch", "--format=%(refname:short)"], repo).stdout.splitlines() if b.strip()
    )
    result.tags = sorted(
        t.strip() for t in run_git(["tag"], repo).stdout.splitlines() if t.strip()
    )
    head = run_git(["rev-parse", "HEAD"], repo, check=False)
    result.head_sha = head.stdout.strip() if head.returncode == 0 else None
    proc2 = run_git(["remote", "get-url", "origin"], repo, check=False)
    result.remote_url = proc2.stdout.strip() if proc2.returncode == 0 else None

    trailers = OrderedDict()  # label -> dict(label, count, sample, raw)
    trailer_re = TRAILER_RE
    msg_proc = run_git(
        ["log", "--all", "--pretty=format:%B%x00"],
        repo,
    )
    for message in msg_proc.stdout.split("\x00"):
        for line in message.splitlines():
            m = trailer_re.match(line.strip())
            if not m:
                continue
            label = m.group(1).lower()
            entry = trailers.setdefault(
                label, {"label": label, "count": 0, "sample": "", "raw": line.strip()}
            )
            entry["count"] += 1
            if not entry["sample"]:
                entry["sample"] = line.strip()
            low = line.lower()
            if any(h in low for h in GENERATED_HINTS):
                result.generated_hint_commits += 1

    if deep:
        blob_proc = run_git(["grep", "-I", "-l", "-i", "-E",
                             "generated by|auto-generated", "--all-match", "--all"], repo, check=False)
        if blob_proc.returncode == 0:
            result.generated_hint_commits += len(blob_proc.stdout.splitlines())

    result.trailers = list(trailers.values())
    return result


def write_scan_report(repo: Path, result: ScanResult, state_dir: Path, audit) -> Path:
    payload = {
        "total_commits": result.total_commits,
        "authors": result.authors,
        "committers": result.committers,
        "trailers": result.trailers,
        "remote_url": result.remote_url,
        "branches": result.branches,
        "tags": result.tags,
        "auto_commits": result.auto_commits,
        "generated_hint_commits": result.generated_hint_commits,
        "head_sha": result.head_sha,
    }
    state_dir.mkdir(parents=True, exist_ok=True)
    out = state_dir / "scan_report.json"
    out.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    audit.log("scan_complete", report=str(out), sha256=_sha(out))
    return out


def _sha(path: Path) -> str:
    import hashlib
    return hashlib.sha256(path.read_bytes()).hexdigest()


if __name__ == "__main__":  # pragma: no cover
    import argparse as _argparse
    _p = _argparse.ArgumentParser(
        prog="gitsanitize_scanner.py",
        description=(
            "gitsanitize library module: scanner.py. This is implementation, "
            "not a standalone CLI -- run scripts/gitsanitize.py instead, "
            "which is the real entry point and imports this module itself."
        ),
    )
    _p.parse_args()  # no arguments defined: --help prints usage and exits 0;
                      # any unexpected argument is argparse's own clean
                      # "unrecognized arguments" error (exit 2), not a traceback
