#!/usr/bin/env python3
"""
AudioSurf Visualizer — Audio Analysis Pipeline Generator

Generates the TypeScript/JavaScript audio analysis module with configurable
FFT size, frequency band splits, beat detection, and spectral feature extraction.

Usage:
    python3 audio_pipeline.py generate [--fft 2048] [--bands 4]
    python3 audio_pipeline.py validate <audio-file>
    python3 audio_pipeline.py status
    python3 audio_pipeline.py --help
    python3 audio_pipeline.py --dry-run
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

STATE_DIR = Path.home() / ".audiosurf-visualizer"
ANALYTICS_DIR = STATE_DIR / "analytics"


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def append_jsonl(filepath, record):
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "a") as f:
        f.write(json.dumps(record) + "\n")


AUDIO_ANALYZER_TEMPLATE = '''// AudioSurf Visualizer — Audio Analysis Engine
// Auto-generated by audio_pipeline.py
// FFT: {fft_size} | Bands: {num_bands} | Smoothing: {smoothing}

export interface FrequencyBands {{
  sub: number;       // 20-60 Hz    — deep sub-bass, track displacement
  bass: number;      // 60-250 Hz   — bass hits, beat pulse, camera shake
  lowMid: number;    // 250-500 Hz  — warmth, ambient glow
  mid: number;       // 500-2000 Hz — melodic content, floating objects
  highMid: number;   // 2-4 kHz     — presence, light beam intensity
  treble: number;    // 4-8 kHz     — sparkle, particle spawning
  brilliance: number;// 8-20 kHz    — shimmer, chromatic aberration
}}

export interface BeatState {{
  isBeat: boolean;
  bpm: number;
  confidence: number;
  timeSinceLastBeat: number;
  beatIntensity: number;  // 0-1 normalized pulse strength
  phase: number;          // 0-1 position within current beat cycle
}}

export interface AudioFeatures {{
  bands: FrequencyBands;
  beat: BeatState;
  energy: number;         // 0-1 overall energy (RMS)
  spectralCentroid: number;
  spectralFlatness: number;
  loudness: number;       // perceived loudness (LUFS-like)
  onset: boolean;         // transient detected
  waveform: Float32Array; // time-domain for oscilloscope effects
}}

export class AudioAnalyzer {{
  private ctx: AudioContext | null = null;
  private analyser: AnalyserNode | null = null;
  private source: MediaElementAudioSourceNode | null = null;
  private freqData: Uint8Array = new Uint8Array(0);
  private timeData: Float32Array = new Float32Array(0);
  private prevEnergy: number = 0;
  private beatHistory: number[] = [];
  private lastBeatTime: number = 0;
  private energyHistory: number[] = [];
  private readonly FFT_SIZE = {fft_size};
  private readonly SMOOTHING = {smoothing};
  private readonly BAND_RANGES: [number, number][] = [
    [20, 60],      // sub
    [60, 250],     // bass
    [250, 500],    // lowMid
    [500, 2000],   // mid
    [2000, 4000],  // highMid
    [4000, 8000],  // treble
    [8000, 20000], // brilliance
  ];

  async init(audioElement: HTMLAudioElement): Promise<void> {{
    this.ctx = new AudioContext();
    if (this.ctx.state === 'suspended') await this.ctx.resume();

    this.analyser = this.ctx.createAnalyser();
    this.analyser.fftSize = this.FFT_SIZE;
    this.analyser.smoothingTimeConstant = this.SMOOTHING;
    this.analyser.minDecibels = -100;
    this.analyser.maxDecibels = -10;

    this.source = this.ctx.createMediaElementSource(audioElement);
    this.source.connect(this.analyser);
    this.analyser.connect(this.ctx.destination);

    const bins = this.analyser.frequencyBinCount;
    this.freqData = new Uint8Array(bins);
    this.timeData = new Float32Array(bins);
  }}

  private hzToBin(hz: number): number {{
    if (!this.ctx || !this.analyser) return 0;
    const nyquist = this.ctx.sampleRate / 2;
    return Math.round((hz / nyquist) * this.analyser.frequencyBinCount);
  }}

  private getBandEnergy(low: number, high: number): number {{
    const lowBin = this.hzToBin(low);
    const highBin = this.hzToBin(high);
    if (highBin <= lowBin) return 0;
    let sum = 0;
    for (let i = lowBin; i < highBin && i < this.freqData.length; i++) {{
      sum += this.freqData[i] / 255;
    }}
    return sum / (highBin - lowBin);
  }}

  private detectBeat(energy: number, now: number): BeatState {{
    this.energyHistory.push(energy);
    if (this.energyHistory.length > 60) this.energyHistory.shift();

    const avgEnergy = this.energyHistory.reduce((a, b) => a + b, 0) / this.energyHistory.length;
    const threshold = avgEnergy * 1.4;
    const isBeat = energy > threshold && (now - this.lastBeatTime) > 200;

    if (isBeat) {{
      this.beatHistory.push(now);
      if (this.beatHistory.length > 16) this.beatHistory.shift();
      this.lastBeatTime = now;
    }}

    // BPM from inter-beat intervals
    let bpm = 120;
    if (this.beatHistory.length >= 4) {{
      const intervals: number[] = [];
      for (let i = 1; i < this.beatHistory.length; i++) {{
        intervals.push(this.beatHistory[i] - this.beatHistory[i - 1]);
      }}
      const avgInterval = intervals.reduce((a, b) => a + b, 0) / intervals.length;
      bpm = Math.round(60000 / avgInterval);
      bpm = Math.max(60, Math.min(200, bpm));
    }}

    const timeSince = now - this.lastBeatTime;
    const beatPeriod = 60000 / bpm;
    const phase = (timeSince % beatPeriod) / beatPeriod;
    const decay = Math.max(0, 1 - timeSince / 150);

    return {{
      isBeat,
      bpm,
      confidence: Math.min(this.beatHistory.length / 8, 1),
      timeSinceLastBeat: timeSince,
      beatIntensity: isBeat ? 1 : decay,
      phase,
    }};
  }}

  getFeatures(): AudioFeatures {{
    if (!this.analyser) {{
      return this.getEmptyFeatures();
    }}

    this.analyser.getByteFrequencyData(this.freqData);
    this.analyser.getFloatTimeDomainData(this.timeData);
    const now = performance.now();

    // Frequency bands
    const bandNames = ['sub', 'bass', 'lowMid', 'mid', 'highMid', 'treble', 'brilliance'] as const;
    const bands = {{}} as FrequencyBands;
    for (let i = 0; i < bandNames.length; i++) {{
      const [low, high] = this.BAND_RANGES[i];
      (bands as any)[bandNames[i]] = this.getBandEnergy(low, high);
    }}

    // RMS energy
    let rms = 0;
    for (let i = 0; i < this.timeData.length; i++) {{
      rms += this.timeData[i] * this.timeData[i];
    }}
    rms = Math.sqrt(rms / this.timeData.length);
    const energy = Math.min(1, rms * 3);

    // Spectral centroid
    let weightedSum = 0, totalMag = 0;
    for (let i = 0; i < this.freqData.length; i++) {{
      weightedSum += i * this.freqData[i];
      totalMag += this.freqData[i];
    }}
    const centroid = totalMag > 0 ? weightedSum / totalMag / this.freqData.length : 0.5;

    // Spectral flatness (geometric / arithmetic mean)
    let logSum = 0, linSum = 0, count = 0;
    for (let i = 1; i < this.freqData.length; i++) {{
      const v = this.freqData[i] / 255 + 1e-10;
      logSum += Math.log(v);
      linSum += v;
      count++;
    }}
    const flatness = count > 0 ? Math.exp(logSum / count) / (linSum / count) : 0;

    // Onset detection (energy derivative)
    const onset = energy - this.prevEnergy > 0.15;
    this.prevEnergy = energy;

    return {{
      bands,
      beat: this.detectBeat(energy, now),
      energy,
      spectralCentroid: centroid,
      spectralFlatness: flatness,
      loudness: energy,
      onset,
      waveform: this.timeData,
    }};
  }}

  private getEmptyFeatures(): AudioFeatures {{
    return {{
      bands: {{ sub: 0, bass: 0, lowMid: 0, mid: 0, highMid: 0, treble: 0, brilliance: 0 }},
      beat: {{ isBeat: false, bpm: 120, confidence: 0, timeSinceLastBeat: Infinity, beatIntensity: 0, phase: 0 }},
      energy: 0,
      spectralCentroid: 0.5,
      spectralFlatness: 0,
      loudness: 0,
      onset: false,
      waveform: new Float32Array(0),
    }};
  }}

  dispose(): void {{
    this.source?.disconnect();
    this.analyser?.disconnect();
    this.ctx?.close();
  }}
}}
'''


def do_generate(args):
    """Generate the audio pipeline TypeScript module."""
    fft_size = 2048
    num_bands = 7
    smoothing = 0.82

    for i, arg in enumerate(args):
        if arg == "--fft" and i + 1 < len(args):
            fft_size = int(args[i + 1])
        if arg == "--bands" and i + 1 < len(args):
            num_bands = int(args[i + 1])
        if arg == "--smoothing" and i + 1 < len(args):
            smoothing = float(args[i + 1])

    code = AUDIO_ANALYZER_TEMPLATE.format(
        fft_size=fft_size,
        num_bands=num_bands,
        smoothing=smoothing,
    )

    output_path = Path("src/audio/AudioAnalyzer.ts")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(code)

    stats = {
        "operation": "generate_audio_pipeline",
        "timestamp": now_iso(),
        "status": "success",
        "config": {"fft_size": fft_size, "bands": num_bands, "smoothing": smoothing},
        "output": str(output_path),
        "cost": {"tier": 0, "amount_usd": 0.0, "service": "local"},
    }
    append_jsonl(ANALYTICS_DIR / "run_stats.jsonl", stats)

    print(f"Generated: {output_path}")
    print(f"FFT size: {fft_size} | Bands: {num_bands} | Smoothing: {smoothing}")
    print(json.dumps(stats, indent=2))


def do_status():
    stats_file = ANALYTICS_DIR / "run_stats.jsonl"
    if stats_file.exists():
        lines = stats_file.read_text().strip().split("\n")
        for line in lines[-5:]:
            print(json.dumps(json.loads(line), indent=2))
    else:
        print("No pipeline runs recorded yet.")


COMMANDS = {
    "generate": do_generate,
    "status": lambda args: do_status(),
    "help": lambda args: print(__doc__),
}


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "help"
    args = sys.argv[2:]

    if cmd in ("--help", "-h"):
        cmd = "help"
    if cmd == "--dry-run":
        print("[DRY RUN] Would generate audio pipeline module")
        return

    if cmd in COMMANDS:
        COMMANDS[cmd](args)
    else:
        print(f"Unknown command: {cmd}")
        print(f"Available: {', '.join(COMMANDS.keys())}")
        sys.exit(1)


if __name__ == "__main__":
    main()
