#!/usr/bin/env python3
"""
AudioSurf Visualizer — Performance Profiler & Adaptive Quality Generator

Generates the adaptive performance tuning system that dynamically scales
visual quality based on real-time FPS to maintain smooth 60fps.

Usage:
    python3 performance_profiler.py generate [--target-fps 60]
    python3 performance_profiler.py benchmark
    python3 performance_profiler.py status
    python3 performance_profiler.py --help
    python3 performance_profiler.py --dry-run
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

STATE_DIR = Path.home() / ".audiosurf-visualizer"
ANALYTICS_DIR = STATE_DIR / "analytics"


def now_iso():
    return datetime.now(timezone.utc).isoformat()


def append_jsonl(filepath, record):
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "a") as f:
        f.write(json.dumps(record) + "\n")


PERF_TUNER_TEMPLATE = '''// AudioSurf Visualizer — Adaptive Performance Tuner
// Auto-generated by performance_profiler.py
// Target FPS: {target_fps} | Profiles: 4 tiers

export type QualityTier = 'potato' | 'low' | 'medium' | 'high' | 'ultra';

export interface PerformanceProfile {{
  tier: QualityTier;
  maxParticles: number;
  maxTrackSegments: number;
  bloomEnabled: boolean;
  bloomIntensity: number;
  chromaticAberration: boolean;
  shadowsEnabled: boolean;
  pixelRatio: number;
  starCount: number;
  floatingObjects: number;
  reflectionsEnabled: boolean;
  motionBlur: boolean;
  fxaaEnabled: boolean;
  volumetricLight: boolean;
  trailLength: number;
}}

const PROFILES: Record<QualityTier, PerformanceProfile> = {{
  potato: {{
    tier: 'potato',
    maxParticles: 50,
    maxTrackSegments: 100,
    bloomEnabled: false,
    bloomIntensity: 0,
    chromaticAberration: false,
    shadowsEnabled: false,
    pixelRatio: 0.75,
    starCount: 200,
    floatingObjects: 3,
    reflectionsEnabled: false,
    motionBlur: false,
    fxaaEnabled: false,
    volumetricLight: false,
    trailLength: 10,
  }},
  low: {{
    tier: 'low',
    maxParticles: 150,
    maxTrackSegments: 300,
    bloomEnabled: true,
    bloomIntensity: 0.4,
    chromaticAberration: false,
    shadowsEnabled: false,
    pixelRatio: 1,
    starCount: 600,
    floatingObjects: 6,
    reflectionsEnabled: false,
    motionBlur: false,
    fxaaEnabled: true,
    volumetricLight: false,
    trailLength: 20,
  }},
  medium: {{
    tier: 'medium',
    maxParticles: 400,
    maxTrackSegments: 800,
    bloomEnabled: true,
    bloomIntensity: 0.7,
    chromaticAberration: true,
    shadowsEnabled: false,
    pixelRatio: Math.min(window.devicePixelRatio, 1.5),
    starCount: 2000,
    floatingObjects: 12,
    reflectionsEnabled: true,
    motionBlur: false,
    fxaaEnabled: true,
    volumetricLight: false,
    trailLength: 40,
  }},
  high: {{
    tier: 'high',
    maxParticles: 800,
    maxTrackSegments: 2000,
    bloomEnabled: true,
    bloomIntensity: 1.0,
    chromaticAberration: true,
    shadowsEnabled: true,
    pixelRatio: Math.min(window.devicePixelRatio, 2),
    starCount: 4000,
    floatingObjects: 20,
    reflectionsEnabled: true,
    motionBlur: true,
    fxaaEnabled: true,
    volumetricLight: true,
    trailLength: 60,
  }},
  ultra: {{
    tier: 'ultra',
    maxParticles: 1500,
    maxTrackSegments: 4000,
    bloomEnabled: true,
    bloomIntensity: 1.3,
    chromaticAberration: true,
    shadowsEnabled: true,
    pixelRatio: window.devicePixelRatio,
    starCount: 8000,
    floatingObjects: 35,
    reflectionsEnabled: true,
    motionBlur: true,
    fxaaEnabled: true,
    volumetricLight: true,
    trailLength: 100,
  }},
}};

export class PerformanceTuner {{
  private profile: PerformanceProfile;
  private fpsHistory: number[] = [];
  private readonly TARGET_FPS = {target_fps};
  private readonly DOWNTICK_THRESHOLD = {target_fps} - 8;  // drop quality
  private readonly UPTICK_THRESHOLD = {target_fps} - 2;    // raise quality
  private readonly SAMPLE_WINDOW = 90;  // frames to average
  private readonly TIER_ORDER: QualityTier[] = ['potato', 'low', 'medium', 'high', 'ultra'];
  private cooldownFrames = 0;
  private readonly COOLDOWN = 120;  // frames between adjustments

  constructor() {{
    this.profile = this.detectHardware();
  }}

  detectHardware(): PerformanceProfile {{
    if (typeof document === 'undefined') return PROFILES.low;

    const canvas = document.createElement('canvas');
    const gl = canvas.getContext('webgl2') || canvas.getContext('webgl');
    if (!gl) return PROFILES.potato;

    const debugInfo = gl.getExtension('WEBGL_debug_renderer_info');
    const gpu = debugInfo ? gl.getParameter(debugInfo.UNMASKED_RENDERER_WEBGL) : '';
    const maxTex = gl.getParameter(gl.MAX_TEXTURE_SIZE);
    const isMobile = /Mobi|Android|iPhone/i.test(navigator.userAgent);

    if (isMobile) return PROFILES.low;
    if (maxTex >= 16384 && /RTX\\s*(30|40)/i.test(gpu)) return PROFILES.ultra;
    if (maxTex >= 8192 && /RTX|Radeon\\s*RX\\s*(6|7)/i.test(gpu)) return PROFILES.high;
    if (maxTex >= 4096) return PROFILES.medium;
    return PROFILES.low;
  }}

  /** Call every frame with current FPS. Returns true if profile changed. */
  tick(currentFps: number): boolean {{
    this.fpsHistory.push(currentFps);
    if (this.fpsHistory.length > this.SAMPLE_WINDOW) this.fpsHistory.shift();
    if (this.cooldownFrames > 0) {{ this.cooldownFrames--; return false; }}
    if (this.fpsHistory.length < 30) return false;

    const avgFps = this.fpsHistory.reduce((a, b) => a + b) / this.fpsHistory.length;
    const currentIdx = this.TIER_ORDER.indexOf(this.profile.tier);

    if (avgFps < this.DOWNTICK_THRESHOLD && currentIdx > 0) {{
      this.profile = PROFILES[this.TIER_ORDER[currentIdx - 1]];
      this.cooldownFrames = this.COOLDOWN;
      this.fpsHistory = [];
      console.log(`[PerfTuner] Downgraded to ${{this.profile.tier}} (avg FPS: ${{avgFps.toFixed(1)}})`);
      return true;
    }}

    if (avgFps >= this.UPTICK_THRESHOLD && currentIdx < this.TIER_ORDER.length - 1) {{
      this.profile = PROFILES[this.TIER_ORDER[currentIdx + 1]];
      this.cooldownFrames = this.COOLDOWN;
      this.fpsHistory = [];
      console.log(`[PerfTuner] Upgraded to ${{this.profile.tier}} (avg FPS: ${{avgFps.toFixed(1)}})`);
      return true;
    }}

    return false;
  }}

  getProfile(): PerformanceProfile {{ return this.profile; }}
  setTier(tier: QualityTier): void {{ this.profile = PROFILES[tier]; }}
  getTier(): QualityTier {{ return this.profile.tier; }}
  getAvgFps(): number {{
    if (this.fpsHistory.length === 0) return 0;
    return this.fpsHistory.reduce((a, b) => a + b) / this.fpsHistory.length;
  }}
}}

// Singleton for app-wide use
export const perfTuner = new PerformanceTuner();
'''


def do_generate(args):
    target_fps = 60
    for i, arg in enumerate(args):
        if arg == "--target-fps" and i + 1 < len(args):
            target_fps = int(args[i + 1])

    code = PERF_TUNER_TEMPLATE.format(target_fps=target_fps)
    output_path = Path("src/systems/PerformanceTuner.ts")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(code)

    stats = {
        "operation": "generate_performance_profiler",
        "timestamp": now_iso(),
        "status": "success",
        "config": {"target_fps": target_fps, "tiers": 5},
        "output": str(output_path),
        "cost": {"tier": 0, "amount_usd": 0.0, "service": "local"},
    }
    append_jsonl(ANALYTICS_DIR / "run_stats.jsonl", stats)
    print(f"Generated: {output_path}")
    print(json.dumps(stats, indent=2))


def do_status():
    stats_file = ANALYTICS_DIR / "run_stats.jsonl"
    if stats_file.exists():
        lines = stats_file.read_text().strip().split("\n")
        for line in lines[-5:]:
            print(json.dumps(json.loads(line), indent=2))
    else:
        print("No profiler runs recorded.")


COMMANDS = {
    "generate": do_generate,
    "status": lambda args: do_status(),
    "help": lambda args: print(__doc__),
}


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "help"
    args = sys.argv[2:]
    if cmd in ("--help", "-h"):
        cmd = "help"
    if cmd == "--dry-run":
        print("[DRY RUN] Would generate performance tuner module")
        return
    if cmd in COMMANDS:
        COMMANDS[cmd](args)
    else:
        print(f"Unknown command: {cmd}")
        sys.exit(1)


if __name__ == "__main__":
    main()
